# Generated by Django 4.2.7 on 2024-04-30 17:00

import apps.nomina.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LicenciaMaternidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha Inicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licencia de Maternidad",
                "verbose_name_plural": "Licencias de Maternidad",
            },
        ),
        migrations.CreateModel(
            name="PagoPorSubsidios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "pago",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Pago Por Subsidios",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PagoPorUtilidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "pago",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Pago Por Utilidades",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalarioEscala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grupo_complejidad",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                        ],
                        max_length=256,
                        verbose_name="Grupo Complejidad",
                    ),
                ),
                (
                    "grupo_escala",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                            ("VII", "VII"),
                            ("VIII", "VIII"),
                            ("IX", "IX"),
                            ("X", "X"),
                            ("XI", "XI"),
                            ("XII", "XII"),
                            ("XIII", "XIII"),
                            ("XIV", "XIV"),
                            ("XV", "XV"),
                            ("XVI", "XVI"),
                            ("XVII", "XVII"),
                            ("XVIII", "XVIII"),
                            ("XIX", "XIX"),
                            ("XX", "XX"),
                            ("XXI", "XXI"),
                            ("XXII", "XXII"),
                            ("XXIII", "XXIII"),
                            ("XXIV", "XXIV"),
                            ("XXV", "XXV"),
                        ],
                        max_length=256,
                        verbose_name="Grupo Escala",
                    ),
                ),
                (
                    "rango_salarial_1",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="I",
                    ),
                ),
                (
                    "rango_salarial_2",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="II",
                    ),
                ),
                (
                    "rango_salarial_3",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="III",
                    ),
                ),
                (
                    "rango_salarial_4",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="IV",
                    ),
                ),
                (
                    "rango_salarial_5",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="V",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salario Escala",
                "verbose_name_plural": "Salarios Escala",
            },
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carnet",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            apps.nomina.models.length_validation_11,
                            django.core.validators.RegexValidator("^[0-9]{11}$"),
                            apps.nomina.models.not_empty_validation,
                        ],
                        verbose_name="Carnet",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$"
                            ),
                            apps.nomina.models.not_empty_validation,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$"
                            ),
                            apps.nomina.models.not_empty_validation,
                        ],
                        verbose_name="Apellidos",
                    ),
                ),
                (
                    "categoria_ocupacional",
                    models.CharField(
                        choices=[
                            ("Categoria1", "Categoria1"),
                            ("Categoria2", "Categoria2"),
                        ],
                        max_length=256,
                        verbose_name="Categoria Ocupacional",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "telefono",
                    models.CharField(
                        max_length=8,
                        unique=True,
                        validators=[
                            apps.nomina.models.length_validation_8,
                            django.core.validators.RegexValidator("^[0-9]{8}$"),
                            apps.nomina.models.not_empty_validation,
                        ],
                        verbose_name="Telefono",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=256, verbose_name="Dirección"),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Economía", "Economía"),
                            ("Desarrollo", "Desarrollo"),
                            ("Dirección", "Dirección"),
                        ],
                        max_length=256,
                        verbose_name="Área",
                    ),
                ),
                (
                    "salario_escala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nomina.salarioescala",
                        verbose_name="Salario Escala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
            },
        ),
        migrations.CreateModel(
            name="SegundaLicenciaPosnatal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha fin",
                    ),
                ),
                (
                    "prestacion_economica",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prestación Económica",
                    ),
                ),
                (
                    "licencia_maternidad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.licenciamaternidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segunda Licencia Posnatal",
                "verbose_name_plural": "Segundas Licencias Posnatal",
            },
        ),
        migrations.CreateModel(
            name="SalarioMensualTotalPagado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "salario_devengado_mensual",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salario Devengado Mensual",
                    ),
                ),
                (
                    "salario_basico_mensual",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salario Basico Mensual",
                    ),
                ),
                (
                    "evaluacion_obtenida_por_el_jefe",
                    models.CharField(
                        choices=[
                            ("D", "Deficiente"),
                            ("R", "Regular"),
                            ("B", "Bien"),
                            ("MB", "Muy Bien"),
                            ("E", "Excelente"),
                        ],
                        max_length=256,
                        verbose_name="Evaluación",
                    ),
                ),
                (
                    "evaluacion_obtenida_por_el_jefe_en_puntos",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Puntos",
                    ),
                ),
                (
                    "pago_por_subsidios",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nomina.pagoporsubsidios",
                        verbose_name="Pago Por Subsidios",
                    ),
                ),
                (
                    "pago_por_utilidades",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nomina.pagoporutilidades",
                        verbose_name="Pago Por Utilidades",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrimeraLicenciaPosnatal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha fin",
                    ),
                ),
                (
                    "prestacion_economica",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prestación Económica",
                    ),
                ),
                (
                    "licencia_maternidad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.licenciamaternidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Primera Licencia Posnatal",
                "verbose_name_plural": "Primeras Licencias Posnatal",
            },
        ),
        migrations.CreateModel(
            name="PrestacionSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha fin",
                    ),
                ),
                (
                    "prestacion_economica",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prestación Económica",
                    ),
                ),
                (
                    "licencia_maternidad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.licenciamaternidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestación Social",
                "verbose_name_plural": "Prestaciones Sociales",
            },
        ),
        migrations.AddField(
            model_name="pagoporutilidades",
            name="trabajador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nomina.trabajador",
                verbose_name="Trabajador",
            ),
        ),
        migrations.AddField(
            model_name="pagoporsubsidios",
            name="trabajador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nomina.trabajador",
                verbose_name="Trabajador",
            ),
        ),
        migrations.CreateModel(
            name="LicenciaPrenatal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha fin",
                    ),
                ),
                ("es_simple", models.BooleanField(default=True)),
                (
                    "prestacion_economica",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prestación Económica",
                    ),
                ),
                (
                    "importe_semanal",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prestación Económica",
                    ),
                ),
                (
                    "salario_anual",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salario Anual",
                    ),
                ),
                (
                    "licencia_maternidad",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.licenciamaternidad",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licencia Prenatal",
                "verbose_name_plural": "Licencias Prenatales",
            },
        ),
        migrations.AddField(
            model_name="licenciamaternidad",
            name="trabajador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nomina.trabajador",
                verbose_name="Trabajador",
            ),
        ),
        migrations.CreateModel(
            name="CertificadoMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha fin",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado Medico",
                "verbose_name_plural": "Certificados Medicos",
                "unique_together": {("trabajador", "fecha_inicio")},
            },
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        validators=[
                            apps.nomina.models.date_not_old_validation,
                            apps.nomina.models.date_not_future_validation,
                        ],
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "horas_trabajadas",
                    models.IntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Horas Trabajadas",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
                "unique_together": {("trabajador", "fecha")},
            },
        ),
    ]
