# Generated by Django 4.2.7 on 2024-04-25 03:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.nomina.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        max_length=256,
                        validators=[apps.nomina.models.not_empty_validation],
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "salario_basico",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salario Basico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
            },
        ),
        migrations.CreateModel(
            name="Escala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        max_length=256,
                        validators=[apps.nomina.models.not_empty_validation],
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "salario_basico",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salario Basico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
            },
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carnet",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            apps.nomina.models.length_validation_11,
                            django.core.validators.RegexValidator("^[0-9]{11}$"),
                            apps.nomina.models.not_empty_validation,
                        ],
                        verbose_name="Carnet",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$"
                            ),
                            apps.nomina.models.not_empty_validation,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$"
                            ),
                            apps.nomina.models.not_empty_validation,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "categoria_ocupacional",
                    models.CharField(
                        choices=[
                            ("Categoria1", "Categoria1"),
                            ("Categoria2", "Categoria2"),
                        ],
                        max_length=256,
                        verbose_name="Categoria Ocupacional",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "telefono",
                    models.CharField(
                        max_length=8,
                        unique=True,
                        validators=[
                            apps.nomina.models.length_validation_8,
                            django.core.validators.RegexValidator("^[0-9]{8}$"),
                            apps.nomina.models.not_empty_validation,
                        ],
                        verbose_name="Telefono",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=256, verbose_name="Dirección"),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Economía", "Economía"),
                            ("Desarrollo", "Desarrollo"),
                            ("Dirección", "Dirección"),
                        ],
                        max_length=256,
                        verbose_name="Área",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.cargo",
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.escala",
                        verbose_name="Escala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
            },
        ),
        migrations.CreateModel(
            name="CertificadoMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha fin",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado Medico",
                "verbose_name_plural": "Certificados Medicos",
                "unique_together": {("trabajador", "fecha_inicio")},
            },
        ),
        migrations.CreateModel(
            name="CertificadoMaternidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        validators=[apps.nomina.models.date_not_old_validation],
                        verbose_name="Fecha fin",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado Medico",
                "verbose_name_plural": "Certificados Medicos",
                "unique_together": {("trabajador", "fecha_inicio")},
            },
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        validators=[
                            apps.nomina.models.date_not_old_validation,
                            apps.nomina.models.date_not_future_validation,
                        ],
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "horas_trabajadas",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas Trabajadas",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomina.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
                "unique_together": {("trabajador", "fecha")},
            },
        ),
    ]
