# Generated by Django 4.2.7 on 2024-04-25 18:28

import apps.nomina.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="escala",
            name="cargo",
        ),
        migrations.AddField(
            model_name="escala",
            name="escala",
            field=models.CharField(
                default="",
                max_length=256,
                validators=[apps.nomina.models.not_empty_validation],
                verbose_name="Escala",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cargo",
            name="cargo",
            field=models.CharField(
                max_length=256,
                validators=[apps.nomina.models.not_empty_validation],
                verbose_name="Cargo",
            ),
        ),
    ]
