# Generated by Django 4.2.7 on 2024-04-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenciaprenatal",
            name="licencia_maternidad",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="nomina.licenciamaternidad",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionsocial",
            name="licencia_maternidad",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="nomina.licenciamaternidad",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionsocial",
            name="segunda_licencia_posnatal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="nomina.segundalicenciaposnatal",
                verbose_name="Segunda Licencia Posnatal",
            ),
        ),
        migrations.AlterField(
            model_name="primeralicenciaposnatal",
            name="licencia_maternidad",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="nomina.licenciamaternidad",
            ),
        ),
        migrations.AlterField(
            model_name="primeralicenciaposnatal",
            name="licencia_prenatal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="nomina.licenciaprenatal",
                verbose_name="Licencia Prenatal",
            ),
        ),
        migrations.AlterField(
            model_name="segundalicenciaposnatal",
            name="primera_licencia_posnatal",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="nomina.primeralicenciaposnatal",
                verbose_name="Primera Licencia Posnatal",
            ),
        ),
    ]
