# Generated by Django 4.2.7 on 2024-05-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificadomedico",
            name="ingresado",
            field=models.BooleanField(default=False, verbose_name="Ingresado"),
        ),
    ]
