# Generated by Django 4.2.7 on 2024-05-01 00:33

import apps.nomina.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salariomensualtotalpagado",
            options={
                "verbose_name": "Salario Mensual",
                "verbose_name_plural": "Salarios Mensuales",
            },
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="horas_trabajadas",
            field=models.IntegerField(
                default=apps.nomina.models.get_horas_correctas,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
                verbose_name="Horas Trabajadas",
            ),
        ),
        migrations.AlterField(
            model_name="licenciaprenatal",
            name="importe_semanal",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prestación Económica",
            ),
        ),
        migrations.AlterField(
            model_name="licenciaprenatal",
            name="prestacion_economica",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prestación Económica",
            ),
        ),
        migrations.AlterField(
            model_name="licenciaprenatal",
            name="salario_anual",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Salario Anual",
            ),
        ),
        migrations.AlterField(
            model_name="pagoporsubsidios",
            name="pago",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pago Por Subsidios",
            ),
        ),
        migrations.AlterField(
            model_name="pagoporutilidades",
            name="pago",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pago Por Utilidades",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionsocial",
            name="prestacion_economica",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prestación Económica",
            ),
        ),
        migrations.AlterField(
            model_name="primeralicenciaposnatal",
            name="prestacion_economica",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prestación Económica",
            ),
        ),
        migrations.AlterField(
            model_name="salariomensualtotalpagado",
            name="salario_basico_mensual",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Salario Basico Mensual",
            ),
        ),
        migrations.AlterField(
            model_name="salariomensualtotalpagado",
            name="salario_devengado_mensual",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Salario Devengado Mensual",
            ),
        ),
        migrations.AlterField(
            model_name="segundalicenciaposnatal",
            name="prestacion_economica",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prestación Económica",
            ),
        ),
    ]
