# Generated by Django 4.2.7 on 2024-04-28 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0002_alter_licenciaprenatal_licencia_maternidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segundalicenciaposnatal",
            name="licencia_maternidad",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="nomina.licenciamaternidad",
            ),
        ),
    ]
