# Generated by Django 4.2.7 on 2024-04-25 19:36

import django.core.validators
from django.db import migrations, models

import apps.nomina.models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0002_remove_escala_cargo_escala_escala_alter_cargo_cargo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="escala",
            options={"verbose_name": "Escala", "verbose_name_plural": "Escalas"},
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="horas_trabajadas",
            field=models.IntegerField(
                default=8,
                validators=[
                    django.core.validators.MinValueValidator(9),
                    django.core.validators.MaxValueValidator(8),
                ],
                verbose_name="Horas Trabajadas",
            ),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="apellidos",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$"),
                    apps.nomina.models.not_empty_validation,
                ],
                verbose_name="Apellidos",
            ),
        ),
    ]
