# Generated by Django 4.2.7 on 2024-05-04 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0002_remove_salariomensualtotalpagado_pago_por_subsidios_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extracertificadomedico",
            name="prestacion_economica",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prestación Económica",
            ),
        ),
        migrations.AlterField(
            model_name="licenciaprenatal",
            name="prestacion_economica",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prestación Económica",
            ),
        ),
        migrations.AlterField(
            model_name="prestacionsocial",
            name="prestacion_economica",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prestación Económica",
            ),
        ),
        migrations.AlterField(
            model_name="primeralicenciaposnatal",
            name="prestacion_economica",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prestación Económica",
            ),
        ),
        migrations.AlterField(
            model_name="primercertificadomedico",
            name="prestacion_economica",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prestación Económica",
            ),
        ),
        migrations.AlterField(
            model_name="salariomensualtotalpagado",
            name="evaluacion_obtenida_por_el_jefe",
            field=models.CharField(
                choices=[
                    ("D", "Deficiente"),
                    ("R", "Regular"),
                    ("B", "Bien"),
                    ("MB", "Muy Bien"),
                    ("E", "Excelente"),
                ],
                default=0,
                max_length=256,
                verbose_name="Evaluación",
            ),
        ),
        migrations.AlterField(
            model_name="salariomensualtotalpagado",
            name="evaluacion_obtenida_por_el_jefe_en_puntos",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Puntos",
            ),
        ),
        migrations.AlterField(
            model_name="salariomensualtotalpagado",
            name="horas_trabajadas",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Horas Trabajadas",
            ),
        ),
        migrations.AlterField(
            model_name="salariomensualtotalpagado",
            name="pago_por_dias_feriados",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pago Dias Feriados",
            ),
        ),
        migrations.AlterField(
            model_name="salariomensualtotalpagado",
            name="salario_basico_mensual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Salario Basico Mensual",
            ),
        ),
        migrations.AlterField(
            model_name="salariomensualtotalpagado",
            name="salario_devengado_mensual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Salario Devengado Mensual",
            ),
        ),
        migrations.AlterField(
            model_name="salariomensualtotalpagado",
            name="trabajador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nomina.trabajador",
                verbose_name="Trabajador",
            ),
        ),
        migrations.AlterField(
            model_name="segundalicenciaposnatal",
            name="prestacion_economica",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prestación Económica",
            ),
        ),
    ]
