# Generated by Django 4.2.7 on 2024-05-04 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0003_alter_extracertificadomedico_prestacion_economica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salariomensualtotalpagado",
            name="pago_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pago Total",
            ),
        ),
        migrations.AddField(
            model_name="salariomensualtotalpagado",
            name="valorar_certificados_maternidad",
            field=models.BooleanField(
                default=True, verbose_name="Valorar Certificados Maternidad"
            ),
        ),
        migrations.AddField(
            model_name="salariomensualtotalpagado",
            name="valorar_certificados_medicos",
            field=models.BooleanField(
                default=True, verbose_name="Valorar Certificados Médicos"
            ),
        ),
        migrations.AddField(
            model_name="salariomensualtotalpagado",
            name="valorar_utilidades",
            field=models.BooleanField(default=True, verbose_name="Valorar Utilidades"),
        ),
    ]
