# Generated by Django 4.2.7 on 2024-04-29 01:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0003_alter_segundalicenciaposnatal_licencia_maternidad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prestacionsocial",
            name="segunda_licencia_posnatal",
        ),
        migrations.RemoveField(
            model_name="primeralicenciaposnatal",
            name="licencia_prenatal",
        ),
        migrations.RemoveField(
            model_name="segundalicenciaposnatal",
            name="primera_licencia_posnatal",
        ),
    ]
