# Generated by Django 4.2.7 on 2024-05-04 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0004_salariomensualtotalpagado_pago_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salariomensualtotalpagado",
            name="pago_certificados_maternidad",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pago Certificados Maternidad",
            ),
        ),
        migrations.AddField(
            model_name="salariomensualtotalpagado",
            name="pago_certificados_medicos",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pago Certificados Médicos",
            ),
        ),
        migrations.AddField(
            model_name="salariomensualtotalpagado",
            name="pago_utilidades",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pago Utilidades",
            ),
        ),
    ]
