# Generated by Django 4.2.7 on 2024-04-29 01:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0004_remove_prestacionsocial_segunda_licencia_posnatal_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="licenciaprenatal",
            unique_together=set(),
        ),
    ]
