# Generated by Django 4.2.7 on 2024-05-06 13:07

import apps.nomina.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_salariomensualtotalpagado_pago_certificados_maternidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoporutilidadesanuales',
            name='pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pago Por Utilidades'),
        ),
        migrations.AlterField(
            model_name='pagoporutilidadesanuales',
            name='pago_extra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='carnet',
            field=models.CharField(max_length=50, unique=True, validators=[apps.nomina.models.length_validation_11, django.core.validators.RegexValidator('^[0-9]{11}$'), apps.nomina.models.not_empty_validation], verbose_name='Carnet'),
        ),
    ]
