# Generated by Django 4.2.7 on 2024-05-08 21:43

import django.utils.timezone
from django.db import migrations, models

import apps.nomina.models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0006_alter_pagoporutilidadesanuales_pago_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="cargo",
            field=models.CharField(
                default="Trabajador",
                max_length=50,
                validators=[apps.nomina.models.not_empty_validation],
                verbose_name="Cargo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trabajador",
            name="sexo",
            field=models.CharField(
                choices=[("Masculino", "Masculino"), ("Femenino", "Femenino")],
                default="Masculino",
                max_length=50,
                verbose_name="Sexo",
            ),
        ),
    ]
