# Generated by Django 4.2.7 on 2024-05-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0007_trabajador_cargo_trabajador_sexo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaFeriado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "nombre",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Día Feriado",
                "verbose_name_plural": "Dias Feriados",
            },
        ),
        migrations.AlterField(
            model_name="certificadomedicogeneral",
            name="descripcion",
            field=models.TextField(blank=True, null=True, verbose_name="Descripción"),
        ),
        migrations.DeleteModel(
            name="PagoPorSubsidios",
        ),
    ]
