# Generated by Django 4.2.7 on 2024-06-01 00:18

import django.contrib.postgres.fields.ranges
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0010_extenciones_postgres"),
    ]

    operations = [
        migrations.AddField(
            model_name="primercertificadomedico",
            name="date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="licenciaprenatal",
            name="importe_semanal",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Importe Semanal",
            ),
        ),
    ]
