# Generated by Django 4.2.7 on 2024-06-01 02:05

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nomina", "0012_extracertificadomedico_date_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciaprenatal",
            name="date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="prestacionsocial",
            name="date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="primeralicenciaposnatal",
            name="date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="segundalicenciaposnatal",
            name="date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True, db_index=True, null=True
            ),
        ),
    ]
